# Site settings
baseurl = "https://socrates-it-test.github.io/"
languageCode = "en-us"
title = "SoCraTes-IT"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-60791139-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "SoCraTes IT"
	description = "International Software Craftsmanship and Testing Conference"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
	#
	# What you need to do for the setup?
	#
	# - set your email address under 'email' below
	# - upload the generated site to your server
	# - send a dummy email yourself to confirm your account
	# - click the confirm link in the email from www.formspree.ioS
	# - you're done. Happy mailing!
	email = "test@gmail.com"
	gforms = "153aAnAaKBsFqusTKXvyZjpgHbKx4LrhPVtn8VubkNKM"

	# Navigation
	[params.navigation]
		brand = "SoCraTes IT 2019"
		services = "It is about"
		portfolio = "Information"
    team = "Partners"
		contact = "Register now"
		sponsors = "Sponsors"

	# Add custom links. Those can be pre- and postpended to the default menu above.
	# Use the weight attribute to order your custom links. Uncomment the example
	# below and replace the values with your own.

	# prepended links
	#[[menu.prepend]]
	#    url = "http://gohugo.io"
	#    name = "Hugo"
	#    weight = 10

	# postpended links
	#[[menu.postpend]]
	#	url = "https://github.com/SoCraTes-it-test/socrates-it-test.github.io"
	#	name = "Wiki"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "April 26-27th, 2019.<br>International Software Craftsmanship and Testing Conference."
		subtitle = "SoCraTes IT 2019"
		buttontext = "Tell me more"

	# Services section
	[params.services]
		enable = true
		title = "It is about"
		subtitle = "This event is about the sustainable creation of useful software in a responsible way."

		[[params.services.row]]

			[[params.services.row.list]]
				icon = "fa-users"
				title = "It's about People"
				description = "Everyone who is concerned with coding, testing, code quality and software craftsmanship. <br />Meet us if you want to share your knowledge, experience and expertise. <br />There is no agenda and there are no speakers before the event starts."

			[[params.services.row.list]]
				icon = "fa-play-circle"
				title = "It's about Action"
				description = "The event will be run as a non-profit, low-cost event. It will be much like a retreat.<br />We will be there for 48 hours to collaborate and share ideas in a self-organized Open Space.<br />There will be hands-on coding sessions, sessions focused on discussion, interactive talks and lots more."

			[[params.services.row.list]]
				icon = "fa-plus-circle"
				title = "It's about Fun"
				description = "We will not only spend the days together but also the nights. And – believe it or not – programmers are a great company! There will be be lots of opportunities to spend your time. Starting with simple chilling over hiking and biking, playing games, hanging around, talking and laughing."

	# Portfolio section
	[params.portfolio]
		enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Information"
		subtitle = "Information"

		[params.portfolio.modal]
			client = "Client"
			date = "Date"
			category = "Category"
			buttontext = "Close"


	# About section
	[params.about]
		enable = false

	# Team section
  [params.team]
		enable = true
		title = "SoCraTes-it is a part of a big family."
		subtitle = "The first “Software Craftsmanship and Testing (un)conference” took place a few years ago in Germany and is organised every year since 2011."
		description = "Other conferences have emerged in other European countries such as SoCraTes UK and SoCraTes Canaries."


		[[params.team.members]]
			name = "SoCraTes Switzerland"
			position = "Switzerland"
			social = [
        ["fa-link", "https://www.socrates-ch.org/"],
        ["fa-twitter", "https://twitter.com/SoCraTes_CH"],
        ["fa-facebook", "https://www.facebook.com/socrates.ch"]
			]


		[[params.team.members]]
			name = "SoCraTes Day Switzerland"
			position = "Switzerland"
			social = [
				["fa-link", "http://socrates-day.ch"],
        ["fa-twitter", "https://twitter.com/SoCraTesDay_CH"],
			]

		[[params.team.members]]
			name = "SoCraTes Canaries"
			position = "Spain"
			social = [
				["fa-link", "http://www.socrates-conference.es"]
			]

		[[params.team.members]]
			name = "SoCraTes UK"
			position = "United Kingdom"
			social = [
				["fa-link", "http://socratesuk.org"],
				["fa-twitter", "https://twitter.com/SoCraTes_UK"]
			]

		[[params.team.members]]
			name = "SoCraTes BE"
			position = "Belgium"
			social = [
				["fa-link", "http://socratesbe.org"],
        ["fa-twitter", "https://twitter.com/SoCraTes_BE"],
        ["fa-github", "https://github.com/socratesbe/socratesbe_18"]
			]

		[[params.team.members]]
			name = "SoCraTes Germany"
			position = "Germany"
			social = [
				["fa-link", "https://www.socrates-conference.de"]
			]

		[[params.team.members]]
			name = "SoCraTes Chile"
			position = "Chile"
			social = [
				["fa-link", "http://www.socrates-conference.cl/"],
        ["fa-twitter", "https://twitter.com/chile_socrates"]
			]


		[[params.team.members]]
			name = "SoCraTes FR"
			position = "France"
			social = [
				["fa-link", "https://socrates-it-test.github.io"],
        ["fa-twitter", "https://twitter.com/SoCraTes_FR"]
			]


    [[params.team.members]]
			name = "SoCraTes Austria"
			position = "Austria"
			social = [
				["fa-link", "https://socrates-conference.at/"]
			]

    [[params.team.members]]
			name = "JSCraftCamp"
			position = "Germany"
			social = [
				["fa-link", "http://jscraftcamp.org/"],
        ["fa-twitter", "https://twitter.com/jscraftcamp"],
        ["fa-github", "https://github.com/jscraftcamp/website"]
			]


		[[params.team.members]]
			name = "CodeFreeze"
			position = "Finland"
			social = [
				["fa-link", "http://www.codefreeze.fi"]
			]

		[[params.team.members]]
			name = "I T.A.K.E. Unconference"
			position = "Romania"
			social = [
				["fa-link", "http://itakeunconf.com"],
        ["fa-twitter", "https://twitter.com/itakeunconf"]
			]


	# Sponsor section
	[params.sponsors]
		enable = true
		title = "Our Sponsors"
		subtitle = ""

		[[params.sponsor]]
 				name = "Aneo"
 				logo = "aneo-square.jpg"
 				link = "http://www.aneo.eu"

		[[params.sponsor]]
			name = "Arolla"
			logo = "arolla-square.jpg"
			link = "http://www.arolla.fr"

		[[params.sponsor]]
			name = "codecentric"
			logo = "codecentric-square.png"
			link = "http://www.codecentric.de"

		[[params.sponsor]]
         	name = "Meritis"
         	logo = "meritis-square.png"
         	link = "http://meritis.fr"

		[[params.sponsor]]
			name = "Novencia"
			logo = "novencia-square.jpg"
			link = "http://www.novencia.com"

# 		[[params.sponsor]]
# 			name = "Viseo Technologies"
# 			logo = "viseo-square.jpg"
# 			link = "http://www.viseo.com"

# 		[[params.sponsor]]
# 			name = "Codurance"
# 			logo = "codurance-square.png"
# 			link = "http://codurance.com"

		[[params.sponsor]]
			name = "Octo Technology"
			logo = "octo-square.png"
			link = "http://www.octo.com"

 		[[params.sponsor]]
 			name = "Orange"
 			logo = "orange-square.png"
 			link = "https://developer.orange.com"

 		[[params.sponsor]]
 				name = "SOAT"
 				logo = "soat-square.png"
 				link = "http://www.soat.fr"

		[[params.sponsor]]
			name = "Zenika"
			logo = "zenika-square.jpg"
			link = "http://www.zenika.com"

	# Client section
	[params.clients_list]
		enable = false

		# All the clients' logos are stored under 'static/img/logos'.
		# Replace them with your clients's logos.
		[[params.clients]]
			logo = "test.jpg"
			link = "http://www.test.fr"


  # Contact section
	[params.contact]
		enable = true
		title = "Registration"
		subtitle  = "The number of participants will be limited to 70."
		buttontext = "Send message"
		explains = """
Prices are per person and include 3 nights accommodation, 3 dinners, 3 lunches, 3 breakfasts and breaks.

| Kind             | Total cost | Information                               |
|------------------|------------|-------------------------------------------|
| single rooms     | 610 €      |                                           |
| double rooms     | 510 €      |                                           |
| triple rooms     | 410 €      | Rooms are big from 25 to 36m² + bathrooms |
| no accommodation | 240 €      | 3 dinners + 3 lunches                     |
"""

	# Footer section
	[params.footer]
		enable = true
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/SoCraTes_FR/"
